---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

## This package should be considered a thought experiment that we are interested to get feedback around the implementation and whether it can help solve your problems.
## It is under development and the API will break as we better understand the problems it is attempting to solve. Use at your own risk.

<hr>

# shredder

<!-- badges: start -->
[![Covrpage
Summary](https://img.shields.io/badge/covrpage-Last_Build_2019_11_19-brightgreen.svg)](http://tinyurl.com/y3zvyrpx)
<!-- badges: end -->

The goal of __shredder__ is to create an API that incites exploration and iteration of rstan simulation objects. 

  - With this API users can: 
    - Manipulate fit objects without needing to convert arrays into recatangular form.
    - Generate task specifc subsets of the parent fit object for fit diagnostics and post-processing
    - Use pipe operators to create more user-friendly workflows
    - Manipulate various classes that contain a `stanfit` object, such as `rstan` and `brms`.
  - RStudio specific feature: Tab autocomplete in `shredder::stan_select` and `shredder::stan_filter` for the parameter names stored in the fit object.

## Installation

``` r
remotes::install_github('metrumresearchgroup/shredder')
```

## Current API Verbs

  - Dimension
      - chains
          - `shredder::stan_retain` : extract specific chains
      - pars
          - `shredder::stan_select` : extract specific pars
          - `shredder::stan_contains`, `shredder::stan_starts_with`,`shredder::stan_ends_with`:
            partial par extractions (used within `shredder::stan_select`)
          - `shredder::stan_names` : return names within the stanfit object
      - post-warmup samples
          - `shredder::stan_slice` : extract specific samples by index
          - `shredder::stan_sample_n` : extract random n samples
          - `shredder::stan_sample_frac` : extract fraction of total samples
          - `shredder::stan_filter` : extract subset of samples conditional on
            filter of parameter values
